run:
  go: "1.24"
  timeout: 5m

linters:
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign

linters-settings:
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
